### ***AUTH TESTS***

### ~SIGN UP~

### Create user
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
  "first_name": "Ana1",
  "last_name": "Lastoviria1",
  "phone_num": "0404040404",
  "email": "ana1@test.com",
  "password": "password1",
  "password_confirmation": "password1"
}
### Create admin
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
  "first_name": "Alex",
  "last_name": "Velasco",
  "phone_num": "0001110303",
  "email": "alex@test.com",
  "password": "password1",
  "password_confirmation": "password1",
  "is_admin": "true"
}
### Unsuccessful user: no first name
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
  "first_name": "",
  "last_name": "Velasco",
  "phone_num": "000444555666",
  "email": "alex@test.com",
  "password": "password1",
  "password_confirmation": "password1"
}
### Unsuccessful user: no last name
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
  "first_name": "Alex",
  "last_name": "",
  "phone_num": "000444555666",
  "email": "alex@test.com",
  "password": "password1",
  "password_confirmation": "password1"
}
### Unsuccessful user: non-numerical + short phone number
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
  "first_name": "Alex",
  "last_name": "Velasco",
  "phone_num": "hi",
  "email": "alex@test.com",
  "password": "password1",
  "password_confirmation": "password1"
}
### Unsuccessful user: invalid email
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
  "first_name": "Alex",
  "last_name": "Velasco",
  "phone_num": "000444555666",
  "email": "hello I am invalid",
  "password": "password1",
  "password_confirmation": "password1"
}

### ~LOG IN~

### Log in with correct password
POST http://localhost:3000/api/auth/log_in
Content-Type: application/json

{
  "email": "alex@test.com",
  "password": "password1"
}
### Unsuccessful log in with incorrect password
POST http://localhost:3000/api/auth/log_in
Content-Type: application/json

{
  "email": "alex@test.com",
  "password": "ljdgkldfjlkdfgj"
}
### Unsuccessful log in with incorrect email
POST http://localhost:3000/api/auth/log_in
Content-Type: application/json

{
  "email": "allkdjglk@test.com",
  "password": "password1"
}

### ~BOOKINGS~

### Get all bookings
GET http://localhost:3000/api/bookings

### Get current user bookings

### Create a booking
POST http://localhost:3000/api/bookings
Content-Type: application/json

{
  "user_id": "1",
  "timeslot_id": "101",
  "venue": "Cool venue",
  "address": "1 Some Or Other Ave, Flemington",
  "event_type": "party",
  "start_time": "12:00pm",
  "duration": "90",
  "message": "Hello it's my mate's birthday party play pls"
}

### Show a single booking
GET http://localhost:3000/api/bookings/2

### Update a booking
PATCH http://localhost:3000/api/bookings/3
Content-Type: application/json

{
  "user_id": "1",
  "timeslot_id": "101",
  "venue": "Cool venue",
  "address": "1 Some Or Other Ave, Flemington",
  "event_type": "party",
  "start_time": "12:00pm",
  "duration": "90",
  "message": "This is an updated message"
}
### Delete a booking
DELETE http://localhost:3000/api/bookings/10