### ***AUTH TESTS***

### ~SIGN UP~

### Create user
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
  "first_name": "Ana1",
  "last_name": "Lastoviria1",
  "phone_num": "0404040404",
  "email": "ana1@test.com",
  "password": "password1",
  "password_confirmation": "password1"
}
### Create admin
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
  "first_name": "Alex",
  "last_name": "Velasco",
  "phone_num": "0001110303",
  "email": "alex@test.com",
  "password": "password1",
  "password_confirmation": "password1",
  "is_admin": "true"
}
### Unsuccessful user: no first name
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
  "first_name": "",
  "last_name": "Velasco",
  "phone_num": "000444555666",
  "email": "alex@test.com",
  "password": "password1",
  "password_confirmation": "password1"
}
### Unsuccessful user: no last name
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
  "first_name": "Alex",
  "last_name": "",
  "phone_num": "000444555666",
  "email": "alex@test.com",
  "password": "password1",
  "password_confirmation": "password1"
}
### Unsuccessful user: non-numerical + short phone number
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
  "first_name": "Alex",
  "last_name": "Velasco",
  "phone_num": "hi",
  "email": "alex@test.com",
  "password": "password1",
  "password_confirmation": "password1"
}
### Unsuccessful user: invalid email
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
  "first_name": "Alex",
  "last_name": "Velasco",
  "phone_num": "000444555666",
  "email": "hello I am invalid",
  "password": "password1",
  "password_confirmation": "password1"
}

### ~LOG IN~

### Log in with correct password
POST http://localhost:3000/api/auth/log_in
Content-Type: application/json

{
  "email": "alex@test.com",
  "password": "password1"
}
### Unsuccessful log in with incorrect password
POST http://localhost:3000/api/auth/log_in
Content-Type: application/json

{
  "email": "alex@test.com",
  "password": "ljdgkldfjlkdfgj"
}
### Unsuccessful log in with incorrect email
POST http://localhost:3000/api/auth/log_in
Content-Type: application/json

{
  "email": "allkdjglk@test.com",
  "password": "password1"
}

### ~BOOKINGS~

### Get all bookings
GET http://localhost:3000/api/bookings
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY2NjUzMzIsInN1YiI6Mn0.WqBvVIcVo-q-0ojRBlIDma7XJl6fh1PWjry7wviT_O8

### Get current user bookings
GET http://localhost:3000/api/my_bookings
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY2NjM3NjgsInN1YiI6NH0.7XzhHV9M2Q6nbq24UvKhnWgpuNuU99DM4usYTr6ojVA


### Create a booking
POST http://localhost:3000/api/bookings
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY2NjM3NjgsInN1YiI6NH0.7XzhHV9M2Q6nbq24UvKhnWgpuNuU99DM4usYTr6ojVA

{
  "timeslot_id": "102",
  "venue": "Madura mansion",
  "address": "1 Some Or Other Ave, Flemington",
  "event_type": "party",
  "start_time": "12:00pm",
  "duration": "90",
  "message": "This should work with a current user"
}

### Unsuccessfuly show someone else's single booking
GET http://localhost:3000/api/bookings/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY2NjM3NjgsInN1YiI6NH0.7XzhHV9M2Q6nbq24UvKhnWgpuNuU99DM4usYTr6ojVA

### Successful show a single booking
GET http://localhost:3000/api/bookings/14
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY2NjM3NjgsInN1YiI6NH0.7XzhHV9M2Q6nbq24UvKhnWgpuNuU99DM4usYTr6ojVA

### Update a booking
PATCH http://localhost:3000/api/bookings/13
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY2NjM3NjgsInN1YiI6NH0.7XzhHV9M2Q6nbq24UvKhnWgpuNuU99DM4usYTr6ojVA

{
  "timeslot_id": "101",
  "venue": "Cool venue",
  "address": "1 Some Or Other Ave, Flemington",
  "event_type": "party",
  "start_time": "12:00pm",
  "duration": "90",
  "message": "This is an updated message"
}

### Delete a booking
DELETE http://localhost:3000/api/bookings/13
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY2NjM3NjgsInN1YiI6NH0.7XzhHV9M2Q6nbq24UvKhnWgpuNuU99DM4usYTr6ojVA

### Unsuccessfuly delete someone else's booking
DELETE http://localhost:3000/api/bookings/13
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY2NjU3MzEsInN1YiI6MX0.fDdieTZWFeFi8DkKiTAv1Vsx5pZVRdDhbVsVuh1cU_Y

### ~CONTACT DETAILS~

### Get all clients for admin
GET http://localhost:3000/api/clients
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY2ODQxMjksInN1YiI6Mn0._rVK8uYuFsL9dLBBB145NuxRcISoqoR9q6zYB8KP5Os

### Get contact details for a user
GET http://localhost:3000/api/my_details
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY2ODM0OTEsInN1YiI6MX0.T0v1aOSX-N5vyBY8SfnglPjaGOqPwGHQNDgQqGio18Y

### User update contact details
PATCH http://localhost:3000/api/my_details
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY2ODQ4NjgsInN1YiI6MX0.vFk2b-JV5X-tPrPHpv4weqscvtuClOIGlW-MNJ0_ewY

{
  "first_name": "Ana",
  "last_name": "Banana",
  "phone_num": "111111111110000",
  "email": "ana@test.com"
}

### User update password
PATCH http://localhost:3000/api/my_details
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY2ODQ4NjgsInN1YiI6MX0.vFk2b-JV5X-tPrPHpv4weqscvtuClOIGlW-MNJ0_ewY

{
  "password": "password0",
  "password_confirmation": "password0"
}

### Delete account
DELETE http://localhost:3000/api/my_details
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY2ODU3ODMsInN1YiI6Nn0.LtbAv_YJLKebmYhFoL4XbCuG0Iv8PG3F4JV1LNhm4Iw


### ~CLIENTS~

### Get all clients with bookings - admin
GET http://localhost:3000/api/clients
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY2ODY5MDEsInN1YiI6Mn0.qeyKoYhL6cLSgikQFk3rtBmUCaANVMlqwauTn5C2gok

### Get client's contact details - admin
GET http://localhost:3000/api/clients/5
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY2ODY5MDEsInN1YiI6Mn0.qeyKoYhL6cLSgikQFk3rtBmUCaANVMlqwauTn5C2gok

### ~TIMESLOTS~

### Successfully block timeslot
PATCH http://localhost:3000/api/edit_availability
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY3MDAxMDIsInN1YiI6Mn0.aG3RZB5RfFTTtH0oSR4MFdljD6dVUjpj7YHx5bDHoH4

{
  "id": "500",
  "is_blocked": "true" 
}

### Successfully release timeslot
PATCH http://localhost:3000/api/edit_availability
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY3MDAxMDIsInN1YiI6Mn0.aG3RZB5RfFTTtH0oSR4MFdljD6dVUjpj7YHx5bDHoH4

{
  "id": "500",
  "is_blocked": "false" 
}

### Get timeslot by date and half_day - admin
POST http://localhost:3000/api/timeslots/get_id
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjcwMTUzOTUsInN1YiI6Mn0.6BFfpGRXpNTMHEhcS4zF7e_lnOlUaHEHd8wAStD7ijs

{
  "date": "2021-08-02",
  "half_day": "one" 
}

### Get timeslot by date and half_day - regular user
POST http://localhost:3000/api/timeslots/get_by_params
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjcwMTgzOTIsInN1YiI6NH0.dTqGRY7EYJyvRQolM0OblGY5kqOQGRIys7BZaCuf86o

{
  "date": "2022-08-02",
  "half_day": "2" 
}